# Generated by Django 3.1.5 on 2021-01-28 11:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iin', models.CharField(max_length=20)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(150), django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
