# Generated by Django 3.1.5 on 2021-01-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iin_to_age', '0002_auto_20210128_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
